Repository inha-talktalk/TalkTalk, pull requests merged in 2023-04, with the labels that each got.

#15 ~2023.03.31 작업사항
  client/.eslintrc.json
  client/.gitignore
  client/.prettierrc.json
  client/README.md
  client/components/Button/index.tsx
  client/components/Footer/index.tsx
  client/components/Footer/style.ts
  client/components/Logo/index.tsx
  client/next.config.js
  client/package.json
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/index.tsx
  client/public/favicon.ico
  client/public/github.svg
  client/public/logo.svg
  client/public/youtube.svg
  client/styles/GlobalThemeContext.tsx
  client/styles/globals.css
  client/styles/theme.ts
  client/tsconfig.json
  client/utils/color.ts
  client/yarn.lock
Labels: FE

#16 Recoil 설치
  client/package.json
  client/pages/_app.tsx
  client/yarn.lock
Labels: FE

#18 UserState 컴포넌트 작성
  client/components/UserState/index.tsx
Labels: FE

#20 NavBar 구현
  client/components/NavBar/index.tsx
  client/components/NavBar/style.ts
Labels: FE

#22 Client CI 추가
  .github/workflows/client-ci.yml
Labels: FE

#23 2023.04.01 작업사항
  .github/workflows/client-ci.yml
  client/components/NavBar/index.tsx
  client/components/NavBar/style.ts
  client/components/UserState/index.tsx
  client/package.json
  client/pages/_app.tsx
  client/yarn.lock
Labels: FE

#25 CD 구축
  .github/workflows/client-cd.yml
  client/README.md
Labels: FE

#26 FE CD 구축
  .github/workflows/client-cd.yml
  client/README.md
Labels: FE

#30 Index 페이지 작성
  client/.env.development
  client/.env.production
  client/components/PostCell/index.tsx
  client/components/PostCell/style.ts
  client/global.d.ts
  client/package.json
  client/pages/api/group-study/list.ts
  client/pages/api/user/profile/[userId].ts
  client/pages/index.tsx
  client/public/main.png
  client/utils/api.ts
  client/yarn.lock
Labels: FE

#33 Client CI에서 캐싱을 하도록 수정
  .github/workflows/client-ci.yml
Labels: FE

#36 BE CI 구축
  .github/workflows/server-ci.yml
Labels: BE

#39 server-ci 수정
  .github/workflows/server-ci.yml
Labels: BE

#40 4/5일 작업사항
  .github/workflows/server-ci.yml
Labels: BE

#41 BE CD 구축
  .github/workflows/server-cd.yml
  server/server.json
Labels: BE

#43 server-ci 설정 변경
  .github/workflows/server-ci.yml
Labels: BE

#42 BE CD 구축
  .github/workflows/server-cd.yml
  .github/workflows/server-ci.yml
  server/server.json
Labels: BE

#46 GNB 및 메인페이지 수정
  client/components/GNB/index.tsx
  client/components/GNB/style.ts
  client/components/Logo/index.tsx
  client/pages/_app.tsx
  client/pages/index.tsx
Labels: FE

#47 Achievement 관련 컴포넌트 작성
  client/components/MyAchievement/index.tsx
  client/components/MyAchievementList/index.tsx
  client/global.d.ts
  client/pages/_app.tsx
  client/pages/api/user/achievement/[userId].ts
  client/pages/index.tsx
  client/pages/selfStudy/index.tsx
  client/utils/api.ts
  client/utils/date.ts
Labels: FE, Refactor

#51 마이페이지 마크업
  client/components/Button/index.tsx
  client/components/GNB/index.tsx
  client/components/GNB/style.ts
  client/components/InputBar/index.tsx
  client/components/LazyImage/index.tsx
  client/components/StudyCard/index.tsx
  client/components/StudyCard/style.ts
  client/components/StudyCardList/Arrow/index.tsx
  client/components/StudyCardList/index.tsx
  client/package.json
  client/pages/_app.tsx
  client/pages/api/group-study/[groupStudyId]/post.ts
  client/pages/myPage/index.tsx
  client/public/arrow.svg
  client/styles/globals.css
  client/utils/image.ts
  client/yarn.lock
Labels: FE

#50 Kakao 로그인 구현
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/inha/server/oauth/ClientConfig.java
  server/src/main/java/com/inha/server/oauth/ClientToken.java
  server/src/main/java/com/inha/server/oauth/KakaoTokens.java
  server/src/main/java/com/inha/server/oauth/OAuthController.java
  server/src/main/java/com/inha/server/oauth/OAuthService.java
  server/src/main/java/com/inha/server/oauth/SocialUserDto.java
  server/src/main/java/com/inha/server/user/User.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: BE

#55 FE 셀프 스터디 진입 페이지 마크업
  client/components/StudyBanner/index.tsx
  client/components/StudyCell/index.tsx
  client/components/StudyCell/style.ts
  client/global.d.ts
  client/pages/api/self-study/[selfStudyId].ts
  client/pages/api/self-study/list.ts
  client/pages/selfStudy/index.tsx
  client/utils/api.ts
Labels: FE, Refactor

#56 fix: StudyCell 마지막 css 적용
  client/pages/selfStudy/index.tsx
Labels: bug, FE

#58 Kakao Login, 회원가입
  server/build.gradle
  server/src/main/java/com/inha/server/ServerApplication.java
  server/src/main/java/com/inha/server/mongodb/config/MongoDbConfig.java
  server/src/main/java/com/inha/server/oauth/KakaoTokens.java
  server/src/main/java/com/inha/server/oauth/OAuthService.java
  server/src/main/java/com/inha/server/oauth/SocialUserDto.java
  server/src/main/java/com/inha/server/oauth/config/ClientConfig.java
  server/src/main/java/com/inha/server/oauth/controller/OAuthController.java
  server/src/main/java/com/inha/server/oauth/dto/JwtDto.java
  server/src/main/java/com/inha/server/oauth/dto/OAuthUserDto.java
  server/src/main/java/com/inha/server/oauth/model/ClientToken.java
  server/src/main/java/com/inha/server/oauth/model/KakaoTokens.java
  server/src/main/java/com/inha/server/oauth/service/OAuthService.java
  server/src/main/java/com/inha/server/security/config/SecurityConfig.java
  server/src/main/java/com/inha/server/security/exception/JwtAccessDeniedHandler.java
  server/src/main/java/com/inha/server/security/exception/JwtAuthenticationEntryPoint.java
  server/src/main/java/com/inha/server/security/jwt/JwtFilter.java
  server/src/main/java/com/inha/server/security/jwt/JwtSecurityConfig.java
  server/src/main/java/com/inha/server/security/jwt/TokenProvider.java
  server/src/main/java/com/inha/server/user/User.java
  server/src/main/java/com/inha/server/user/model/User.java
  server/src/main/java/com/inha/server/user/repository/UserRepository.java
Labels: BE

#59 스터디 그룹 생성 페이지 마크업
  client/components/InputBar/index.tsx
  client/components/TagInputBar/index.tsx
  client/components/TagInputBar/style.ts
  client/components/TextArea/index.tsx
  client/components/TitleInputBar/index.tsx
  client/package.json
  client/pages/_app.tsx
  client/pages/createStudyGroup/index.tsx
  client/styles/calendar.css
  client/yarn.lock
Labels: FE

#60 ~2023.04.15 작업사항
  client/components/InputBar/index.tsx
  client/components/StudyBanner/index.tsx
  client/components/StudyCell/index.tsx
  client/components/StudyCell/style.ts
  client/components/TagInputBar/index.tsx
  client/components/TagInputBar/style.ts
  client/components/TextArea/index.tsx
  client/components/TitleInputBar/index.tsx
  client/global.d.ts
  client/package.json
  client/pages/_app.tsx
  client/pages/api/self-study/[selfStudyId].ts
  client/pages/api/self-study/list.ts
  client/pages/createStudyGroup/index.tsx
  client/pages/selfStudy/index.tsx
  client/styles/calendar.css
  client/utils/api.ts
  client/yarn.lock
  server/build.gradle
  server/src/main/java/com/inha/server/ServerApplication.java
  server/src/main/java/com/inha/server/mongodb/config/MongoDbConfig.java
  server/src/main/java/com/inha/server/oauth/KakaoTokens.java
  server/src/main/java/com/inha/server/oauth/OAuthService.java
  server/src/main/java/com/inha/server/oauth/SocialUserDto.java
  server/src/main/java/com/inha/server/oauth/config/ClientConfig.java
  server/src/main/java/com/inha/server/oauth/controller/OAuthController.java
  server/src/main/java/com/inha/server/oauth/dto/JwtDto.java
  server/src/main/java/com/inha/server/oauth/dto/OAuthUserDto.java
  server/src/main/java/com/inha/server/oauth/model/ClientToken.java
  server/src/main/java/com/inha/server/oauth/model/KakaoTokens.java
  server/src/main/java/com/inha/server/oauth/service/OAuthService.java
  server/src/main/java/com/inha/server/security/config/SecurityConfig.java
  server/src/main/java/com/inha/server/security/exception/JwtAccessDeniedHandler.java
  server/src/main/java/com/inha/server/security/exception/JwtAuthenticationEntryPoint.java
  server/src/main/java/com/inha/server/security/jwt/JwtFilter.java
  server/src/main/java/com/inha/server/security/jwt/JwtSecurityConfig.java
  server/src/main/java/com/inha/server/security/jwt/TokenProvider.java
  server/src/main/java/com/inha/server/user/User.java
  server/src/main/java/com/inha/server/user/model/User.java
  server/src/main/java/com/inha/server/user/repository/UserRepository.java
Labels: FE, BE

#68 카카오 로그인 API POST 변경 적용
  client/utils/api.ts
Labels: FE

#69 스터디 그룹 검색 페이지 마크업
  client/global.d.ts
  client/pages/api/group-study/index.ts
  client/pages/findStudyGroup/index.tsx
  client/utils/api.ts
Labels: FE

#72 그룹 스터디 상세 페이지 마크업
  client/pages/postView/index.tsx
Labels: FE

#74 카카오 로그인 시 프로필 uri 받아오도록
  server/src/main/java/com/inha/server/oauth/dto/OAuthUserDto.java
  server/src/main/java/com/inha/server/oauth/model/ClientToken.java
  server/src/main/java/com/inha/server/oauth/service/OAuthService.java
Labels: BE

#75 ~2023.04.21 작업사항
  client/.env.development
  client/.env.production
  client/components/GNB/index.tsx
  client/components/LoginButton/index.tsx
  client/components/UserState/index.tsx
  client/global.d.ts
  client/next.config.js
  client/pages/api/group-study/index.ts
  client/pages/findStudyGroup/index.tsx
  client/pages/login/index.tsx
  client/pages/oauth/kakao.tsx
  client/pages/postView/index.tsx
  client/public/kakaoLogin.png
  client/states/login.ts
  client/utils/api.ts
  server/src/main/java/com/inha/server/oauth/controller/OAuthController.java
  server/src/main/java/com/inha/server/oauth/dto/OAuthUserDto.java
  server/src/main/java/com/inha/server/oauth/model/ClientToken.java
  server/src/main/java/com/inha/server/oauth/service/OAuthService.java
Labels: FE, BE

#78 hotfix: server CI 수정
  .github/workflows/server-ci.yml
Labels: bug, BE

#79 Server CI 수정
  .github/workflows/server-ci.yml
Labels: bug, BE

#82 스터디 그룹 생성 및 목록 조회
  server/src/main/java/com/inha/server/oauth/controller/OAuthController.java
  server/src/main/java/com/inha/server/oauth/security/SecurityConfig.java
  server/src/main/java/com/inha/server/oauth/service/OAuthService.java
  server/src/main/java/com/inha/server/security/config/SecurityConfig.java
  server/src/main/java/com/inha/server/security/exception/JwtAccessDeniedHandler.java
  server/src/main/java/com/inha/server/security/exception/JwtAuthenticationEntryPoint.java
  server/src/main/java/com/inha/server/security/jwt/JwtFilter.java
  server/src/main/java/com/inha/server/security/jwt/JwtSecurityConfig.java
  server/src/main/java/com/inha/server/security/jwt/TokenProvider.java
  server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
  server/src/main/java/com/inha/server/study/group/dto/request/PostGroupStudyReq.java
  server/src/main/java/com/inha/server/study/group/dto/response/GetGroupStudyListRes.java
  server/src/main/java/com/inha/server/study/group/dto/response/GroupStudyRes.java
  server/src/main/java/com/inha/server/study/group/dto/response/PostGroupStudyRes.java
  server/src/main/java/com/inha/server/study/group/model/GroupStudy.java
  server/src/main/java/com/inha/server/study/group/repository/GroupStudyRepository.java
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
  server/src/main/java/com/inha/server/user/model/User.java
  server/src/main/java/com/inha/server/user/util/TokenProvider.java
Labels: BE

#84 BE 스터디 그룹 게시글 상세조회, 스터디 종료
  server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
  server/src/main/java/com/inha/server/study/group/dto/response/DeleteGroupStudyRes.java
  server/src/main/java/com/inha/server/study/group/dto/response/GetGroupStudyDetailRes.java
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
Labels: BE

#85 마이페이지 기능 구현 (1) 프로필
  server/.gitignore
  server/src/main/java/com/inha/server/mypage/controller/MayPageController.java
  server/src/main/java/com/inha/server/mypage/dto/request/ProfileNameAndNicknameReq.java
  server/src/main/java/com/inha/server/mypage/dto/response/ProfileInfoRes.java
  server/src/main/java/com/inha/server/mypage/service/MyPageService.java
  server/src/main/java/com/inha/server/oauth/dto/OAuthUserDto.java
  server/src/main/java/com/inha/server/oauth/service/OAuthService.java
  server/src/main/java/com/inha/server/user/model/User.java
Labels: BE

#86 ~2023.04.26 작업사항
  server/.gitignore
  server/src/main/java/com/inha/server/mypage/controller/MayPageController.java
  server/src/main/java/com/inha/server/mypage/dto/request/ProfileNameAndNicknameReq.java
  server/src/main/java/com/inha/server/mypage/dto/response/ProfileInfoRes.java
  server/src/main/java/com/inha/server/mypage/service/MyPageService.java
  server/src/main/java/com/inha/server/oauth/controller/OAuthController.java
  server/src/main/java/com/inha/server/oauth/dto/OAuthUserDto.java
  server/src/main/java/com/inha/server/oauth/security/SecurityConfig.java
  server/src/main/java/com/inha/server/oauth/service/OAuthService.java
  server/src/main/java/com/inha/server/security/config/SecurityConfig.java
  server/src/main/java/com/inha/server/security/exception/JwtAccessDeniedHandler.java
  server/src/main/java/com/inha/server/security/exception/JwtAuthenticationEntryPoint.java
  server/src/main/java/com/inha/server/security/jwt/JwtFilter.java
  server/src/main/java/com/inha/server/security/jwt/JwtSecurityConfig.java
  server/src/main/java/com/inha/server/security/jwt/TokenProvider.java
  server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
  server/src/main/java/com/inha/server/study/group/dto/request/PostGroupStudyReq.java
  server/src/main/java/com/inha/server/study/group/dto/response/DeleteGroupStudyRes.java
  server/src/main/java/com/inha/server/study/group/dto/response/GetGroupStudyDetailRes.java
  server/src/main/java/com/inha/server/study/group/dto/response/GetGroupStudyListRes.java
  server/src/main/java/com/inha/server/study/group/dto/response/GroupStudyRes.java
  server/src/main/java/com/inha/server/study/group/dto/response/PostGroupStudyRes.java
  server/src/main/java/com/inha/server/study/group/model/GroupStudy.java
  server/src/main/java/com/inha/server/study/group/repository/GroupStudyRepository.java
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
  server/src/main/java/com/inha/server/user/model/User.java
  server/src/main/java/com/inha/server/user/util/TokenProvider.java
Labels: BE

#89 FE dev, prod 설정 분리
  client/.env.production
  client/next.config.js
Labels: FE

#88 마이페이지 기능 구현 (1) 프로필
  server/build.gradle
  server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
  server/src/main/java/com/inha/server/mypage/service/MyPageService.java
  server/src/main/java/com/inha/server/s3/config/AwsS3Config.java
  server/src/main/java/com/inha/server/s3/service/S3Service.java
  server/src/main/java/com/inha/server/user/model/User.java
Labels: BE

#92 로그인이 유지되지 않는 문제 수정
  client/components/UserState/index.tsx
  client/pages/oauth/kakao.tsx
  client/states/login.ts
Labels: bug, FE

#93 jwt 없이 user 정보 조회 가능하도록, 에러 발생 시 404 응답하도록
  server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
  server/src/main/java/com/inha/server/mypage/service/MyPageService.java
Labels: BE

#94 회원 정보 조회 self 추가
  server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
  server/src/main/java/com/inha/server/mypage/service/MyPageService.java
Labels: BE

#95 다른 유저 정보 조회 성공시 404 반환 오류 해결
  server/src/main/java/com/inha/server/mypage/service/MyPageService.java
Labels: bug, BE

#96 프로필 닉네임 & 이름 수정 오류 해결
  server/src/main/java/com/inha/server/mypage/dto/request/ProfileNameAndNicknameReq.java
Labels: bug, BE

#99 마이페이지 Mock API 작성
  server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
  server/src/main/java/com/inha/server/mypage/dto/response/AchievementRes.java
  server/src/main/java/com/inha/server/mypage/dto/response/MyStudiesRes.java
Labels: BE

#97 마이페이지 API 연결 (일부)
  client/components/GNB/index.tsx
  client/next.config.js
  client/pages/api/group-study/list.ts
  client/pages/api/v0/profile/[userId].ts
  client/pages/myPage/index.tsx
  client/pages/oauth/kakao.tsx
  client/utils/api.ts
Labels: FE

#100 BE 스터디 그룹 가입 신청, 가입 신청 목록 조회, 가입 수락
  server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
  server/src/main/java/com/inha/server/study/group/dto/response/PostGroupStudyAcceptRes.java
  server/src/main/java/com/inha/server/study/group/dto/response/WaitingListRes.java
  server/src/main/java/com/inha/server/study/group/model/GroupStudy.java
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
Labels: BE
