Repository inha-talktalk/TalkTalk, pull requests merged in 2023-05, with the labels that each got.

#105 Swagger 적용
  server/build.gradle
  server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
  server/src/main/java/com/inha/server/mypage/dto/response/ProfileInfoRes.java
  server/src/main/java/com/inha/server/swagger/config/SwaggerConfig.java
Labels: BE

#104 ~2023.05.01 작업사항
  client/.env.production
  client/components/ChatBubble/index.tsx
  client/components/ChatInputBar/index.tsx
  client/components/CreateSelfStudy/index.tsx
  client/components/CreateSelfStudy/style.ts
  client/components/GNB/index.tsx
  client/components/InfoBanner/index.tsx
  client/components/SelfStudyController/index.tsx
  client/components/SelfStudyController/style.ts
  client/components/SelfStudyPanel/index.tsx
  client/components/StudyBanner/index.tsx
  client/components/TitleInputBar/index.tsx
  client/components/UserState/index.tsx
  client/next.config.js
  client/package.json
  client/pages/api/group-study/list.ts
  client/pages/api/user/achieve.ts
  client/pages/api/v0/profile/[userId].ts
  client/pages/createStudyGroup/index.tsx
  client/pages/myPage/index.tsx
  client/pages/oauth/kakao.tsx
  client/pages/selfStudy/create/read.tsx
  client/pages/selfStudy/create/write.tsx
  client/pages/selfStudy/index.tsx
  client/pages/selfStudy/read.tsx
  client/pages/selfStudy/write.tsx
  client/states/login.ts
  client/utils/api.ts
  client/yarn.lock
  server/build.gradle
  server/src/main/java/com/inha/server/mypage/controller/MayPageController.java
  server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
  server/src/main/java/com/inha/server/mypage/dto/request/ProfileNameAndNicknameReq.java
  server/src/main/java/com/inha/server/mypage/dto/response/AchievementRes.java
  server/src/main/java/com/inha/server/mypage/dto/response/MyStudiesRes.java
  server/src/main/java/com/inha/server/mypage/dto/response/ProfileInfoRes.java
  server/src/main/java/com/inha/server/mypage/service/MyPageService.java
  server/src/main/java/com/inha/server/s3/config/AwsS3Config.java
  server/src/main/java/com/inha/server/s3/service/S3Service.java
  server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
  server/src/main/java/com/inha/server/study/group/dto/response/PostGroupStudyAcceptRes.java
  server/src/main/java/com/inha/server/study/group/dto/response/WaitingListRes.java
  server/src/main/java/com/inha/server/study/group/model/GroupStudy.java
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
  server/src/main/java/com/inha/server/swagger/config/SwaggerConfig.java
  server/src/main/java/com/inha/server/user/model/User.java
Labels: bug, FE, BE

#112 FE 그룹 스터디 생성, 그룹 스터디 신청 페이지 API 연결
  client/components/PostCell/index.tsx
  client/global.d.ts
  client/pages/api/group-study/[groupStudyId]/post.ts
  client/pages/api/language.ts
  client/pages/createStudyGroup/index.tsx
  client/pages/postView/[groupStudyId].tsx
  client/utils/api.ts
Labels: FE

#113 마이페이지 기능 구현 (2) 스터디 목록
  server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
  server/src/main/java/com/inha/server/mypage/service/MyPageService.java
  server/src/main/java/com/inha/server/study/group/model/ApplyStatus.java
  server/src/main/java/com/inha/server/study/group/repository/ApplyStatusRepository.java
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
Labels: BE

#116 FE 마이페이지 스터디 목록 연동
  client/components/StudyCardList/index.tsx
  client/global.d.ts
  client/pages/myPage/index.tsx
  client/utils/api.ts
Labels: FE

#118 FE 셀프 스터디 공유 모달 구현
  client/components/Modal/index.tsx
  client/components/Modal/style.ts
  client/components/SelfStudySharePanel/index.tsx
  client/components/SelfStudySharePanel/style.ts
Labels: FE

#121 Chat GPT API 연동
  server/src/main/java/com/inha/server/chatGPT/config/OpenAIRestTemplateConfig.java
  server/src/main/java/com/inha/server/chatGPT/controller/ChatController.java
  server/src/main/java/com/inha/server/chatGPT/dto/Message.java
  server/src/main/java/com/inha/server/chatGPT/dto/request/ChatReq.java
  server/src/main/java/com/inha/server/chatGPT/dto/response/ChatRes.java
Labels: BE

#128 사용자가 생성한 스터디도 스터디 목록에 추가되도록 수정
  server/src/main/java/com/inha/server/mypage/service/MyPageService.java
  server/src/main/java/com/inha/server/study/group/repository/GroupStudyRepository.java
Labels: bug, BE

#129 BE 스터디 마감 기한 관련 오류 해결
  server/src/main/java/com/inha/server/study/group/dto/request/PostGroupStudyReq.java
  server/src/main/java/com/inha/server/study/group/model/GroupStudy.java
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
Labels: BE, Refactor

#131 ✨feat: CORS allow origin 추가
  server/src/main/java/com/inha/server/oauth/security/SecurityConfig.java
Labels: BE

#134 FE 그룹 스터디 페이지 마크업
  client/components/ChatInputBar/index.tsx
  client/components/GroupStudyChat/ChatSlot/index.tsx
  client/components/GroupStudyChat/ChatSlot/style.ts
  client/components/GroupStudyChat/Divider/index.tsx
  client/components/GroupStudyChat/index.tsx
  client/components/GroupStudyChat/style.ts
  client/components/GroupStudyController/GroupStudyChannel/index.tsx
  client/components/GroupStudyController/GroupStudyChannel/style.ts
  client/components/GroupStudyController/GroupStudySettingController/index.tsx
  client/components/GroupStudyController/GroupStudySettingController/style.ts
  client/components/GroupStudyController/GroupStudyVoiceChannel/index.tsx
  client/components/GroupStudyController/GroupStudyVoiceChannel/style.ts
  client/components/GroupStudyController/StudyInfo/index.tsx
  client/components/GroupStudyController/StudyInfo/style.ts
  client/components/GroupStudyController/index.tsx
  client/components/GroupStudyController/style.ts
  client/components/MyAchievementList/index.tsx
  client/components/StudyCard/index.tsx
  client/components/StudyCardList/index.tsx
  client/components/UserList/index.tsx
  client/components/UserList/style.ts
  client/components/UserSlot/index.tsx
  client/global.d.ts
  client/package.json
  client/pages/_app.tsx
  client/pages/api/group-study/[groupStudyId]/post.ts
  client/pages/api/group-study/list.ts
  client/pages/studyGroup/[groupId].tsx
  client/pages/studyGroup/index.tsx
  client/states/groupStudy.ts
  client/utils/api.ts
  client/yarn.lock
Labels: FE, Refactor

#135 2023.05.12 작업사항 - 그룹 스터디 페이지 마크업
  client/components/ChatInputBar/index.tsx
  client/components/GroupStudyChat/ChatSlot/index.tsx
  client/components/GroupStudyChat/ChatSlot/style.ts
  client/components/GroupStudyChat/Divider/index.tsx
  client/components/GroupStudyChat/index.tsx
  client/components/GroupStudyChat/style.ts
  client/components/GroupStudyController/GroupStudyChannel/index.tsx
  client/components/GroupStudyController/GroupStudyChannel/style.ts
  client/components/GroupStudyController/GroupStudySettingController/index.tsx
  client/components/GroupStudyController/GroupStudySettingController/style.ts
  client/components/GroupStudyController/GroupStudyVoiceChannel/index.tsx
  client/components/GroupStudyController/GroupStudyVoiceChannel/style.ts
  client/components/GroupStudyController/StudyInfo/index.tsx
  client/components/GroupStudyController/StudyInfo/style.ts
  client/components/GroupStudyController/index.tsx
  client/components/GroupStudyController/style.ts
  client/components/MyAchievementList/index.tsx
  client/components/StudyCard/index.tsx
  client/components/StudyCardList/index.tsx
  client/components/UserList/index.tsx
  client/components/UserList/style.ts
  client/components/UserSlot/index.tsx
  client/global.d.ts
  client/package.json
  client/pages/_app.tsx
  client/pages/api/group-study/[groupStudyId]/post.ts
  client/pages/api/group-study/list.ts
  client/pages/studyGroup/[groupId].tsx
  client/pages/studyGroup/index.tsx
  client/states/groupStudy.ts
  client/utils/api.ts
  client/yarn.lock
Labels: FE, Refactor

#143 fix: application.yml 제거 적용
  .github/workflows/server-ci.yml
Labels: bug, BE

#142 gitignore 에 application.yml 추가
  .github/workflows/server-ci.yml
  server/.gitignore
  server/src/main/resources/application.yml
Labels: BE

#150 FE 그룹스터디 설정 모달 마크업
  client/components/GroupStudyController/GroupStudySetting/index.tsx
  client/components/GroupStudyController/GroupStudySetting/style.ts
  client/components/GroupStudyController/GroupStudySettingController/index.tsx
  client/components/UserSlot/index.tsx
  client/styles/globals.css
Labels: FE

#152 BE 셀프 스터디 생성 Mock API 생성 & 지원 언어 제공 API 구현
  server/src/main/java/com/inha/server/language/controller/LanguageController.java
  server/src/main/java/com/inha/server/language/dto/response/LanguageDto.java
  server/src/main/java/com/inha/server/language/enumtype/language.java
  server/src/main/java/com/inha/server/language/model/Language.java
  server/src/main/java/com/inha/server/language/repository/LanguageRepository.java
  server/src/main/java/com/inha/server/language/service/LanguageService.java
  server/src/main/java/com/inha/server/study/self/controller/SelfStudyController.java
  server/src/main/java/com/inha/server/study/self/dto/reponse/ScriptDto.java
Labels: BE

#154 FE 그룹 스터디 검색 API 수정에 따른 변경
  client/components/GNB/index.tsx
  client/components/GroupStudyChat/ChatSlot/style.ts
  client/components/GroupStudyController/GroupStudySettingController/style.ts
  client/components/GroupStudyController/index.tsx
  client/global.d.ts
  client/pages/api/group-study/[groupStudyId]/post.ts
  client/pages/api/group-study/index.ts
  client/pages/api/group-study/list.ts
  client/pages/api/v0/profile/[userId].ts
  client/pages/findStudyGroup/index.tsx
  client/pages/index.tsx
  client/pages/studyGroup/[groupId].tsx
  client/styles/globals.css
  client/utils/api.ts
Labels: bug, FE

#156 BE API 예외처리 로직 추가
  server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
Labels: BE, Refactor

#159 FE /language API 적용
  client/components/CreateSelfStudy/index.tsx
  client/pages/api/language.ts
  client/pages/createStudyGroup/index.tsx
Labels: FE

#161 스크립트 타입 제공 API 추가 & Swagger Contorller 추가
  server/src/main/java/com/inha/server/language/controller/LanguageController.java
  server/src/main/java/com/inha/server/language/dto/response/ScriptTypeDto.java
  server/src/main/java/com/inha/server/swagger/config/SwaggerConfig.java
Labels: BE

#162 FE react-toast 적용
  client/components/CreateSelfStudy/index.tsx
  client/package.json
  client/pages/_app.tsx
  client/pages/createStudyGroup/index.tsx
  client/pages/myPage/index.tsx
  client/pages/oauth/kakao.tsx
  client/pages/postView/[groupStudyId].tsx
  client/yarn.lock
Labels: FE

#164 스크립트 타입 API 연동 및 버그 수정
  client/components/CreateSelfStudy/index.tsx
  client/components/StudyCardList/index.tsx
  client/global.d.ts
  client/pages/findStudyGroup/index.tsx
  client/utils/api.ts
Labels: bug, FE

#167 BE response status code 수정
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
Labels: BE, Refactor

#171 BE 스터디 생성 API 구현
  server/src/main/java/com/inha/server/chatGPT/controller/ChatController.java
  server/src/main/java/com/inha/server/chatGPT/model/Script.java
  server/src/main/java/com/inha/server/chatGPT/repository/ScriptRepository.java
  server/src/main/java/com/inha/server/chatGPT/service/ScriptService.java
  server/src/main/java/com/inha/server/study/self/controller/SelfStudyController.java
  server/src/main/java/com/inha/server/study/self/dto/reponse/ScriptDto.java
  server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java
  server/src/main/java/com/inha/server/user/model/UserScriptList.java
  server/src/main/java/com/inha/server/user/repository/UserScriptRepository.java
Labels: BE

#172 API 일부 명명 수정
  server/src/main/java/com/inha/server/chatGPT/controller/ChatController.java
  server/src/main/java/com/inha/server/chatGPT/dto/request/ScriptReq.java
  server/src/main/java/com/inha/server/language/controller/LanguageController.java
Labels: BE, Refactor

#173 ~2023.05.22 작업사항
  client/components/CreateSelfStudy/index.tsx
  client/components/GNB/index.tsx
  client/components/GroupStudyChat/ChatSlot/style.ts
  client/components/GroupStudyController/GroupStudySetting/index.tsx
  client/components/GroupStudyController/GroupStudySetting/style.ts
  client/components/GroupStudyController/GroupStudySettingController/index.tsx
  client/components/GroupStudyController/GroupStudySettingController/style.ts
  client/components/GroupStudyController/index.tsx
  client/components/StudyCardList/index.tsx
  client/components/UserSlot/index.tsx
  client/global.d.ts
  client/package.json
  client/pages/_app.tsx
  client/pages/api/group-study/[groupStudyId]/post.ts
  client/pages/api/group-study/index.ts
  client/pages/api/group-study/list.ts
  client/pages/api/language.ts
  client/pages/api/v0/profile/[userId].ts
  client/pages/createStudyGroup/index.tsx
  client/pages/findStudyGroup/index.tsx
  client/pages/index.tsx
  client/pages/myPage/index.tsx
  client/pages/oauth/kakao.tsx
  client/pages/postView/[groupStudyId].tsx
  client/pages/studyGroup/[groupId].tsx
  client/styles/globals.css
  client/utils/api.ts
  client/yarn.lock
  server/src/main/java/com/inha/server/chatGPT/controller/ChatController.java
  server/src/main/java/com/inha/server/chatGPT/dto/request/ChatReq.java
  server/src/main/java/com/inha/server/chatGPT/dto/request/ScriptReq.java
  server/src/main/java/com/inha/server/chatGPT/model/Script.java
  server/src/main/java/com/inha/server/chatGPT/repository/ScriptRepository.java
  server/src/main/java/com/inha/server/chatGPT/service/ScriptService.java
  server/src/main/java/com/inha/server/clova/service/ClovaService.java
  server/src/main/java/com/inha/server/language/controller/LanguageController.java
  server/src/main/java/com/inha/server/language/dto/response/LanguageDto.java
  server/src/main/java/com/inha/server/language/dto/response/ScriptTypeDto.java
  server/src/main/java/com/inha/server/language/enumtype/language.java
  server/src/main/java/com/inha/server/language/model/Language.java
  server/src/main/java/com/inha/server/language/repository/LanguageRepository.java
  server/src/main/java/com/inha/server/language/service/LanguageService.java
  server/src/main/java/com/inha/server/s3/service/S3Service.java
  server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
  server/src/main/java/com/inha/server/study/group/dto/response/GroupStudyRes.java
  server/src/main/java/com/inha/server/study/group/model/GroupStudy.java
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
  server/src/main/java/com/inha/server/study/self/controller/SelfStudyController.java
  server/src/main/java/com/inha/server/study/self/dto/reponse/ScriptDto.java
  server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java
  server/src/main/java/com/inha/server/swagger/config/SwaggerConfig.java
  server/src/main/java/com/inha/server/user/model/UserScriptList.java
  server/src/main/java/com/inha/server/user/repository/UserScriptRepository.java
Labels: bug, FE, BE, Refactor

#175 🚑 hotfix: 스크립트 타입 API 경로 수정
  client/utils/api.ts
Labels: bug, FE

#176 hotfix: 스크립트 타입 API 경로 수정
  client/utils/api.ts
Labels: bug, FE

#178 BE hotfix 검색 API, 그룹 스터디 정보 조회 API 수정
  server/src/main/java/com/inha/server/study/group/dto/response/GetGroupStudyInfoRes.java
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
Labels: bug, BE, Refactor

#180 BE hotfix 그룹 스터디 리스트 조회, 검색 API 수정
  server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
Labels: BE, Refactor

#181 BE 셀프 스터디 시작, 종료, 취소 구현
  server/src/main/java/com/inha/server/chatGPT/model/Script.java
  server/src/main/java/com/inha/server/study/self/controller/SelfStudyController.java
  server/src/main/java/com/inha/server/study/self/dto/reponse/SelfStudyCreateRes.java
  server/src/main/java/com/inha/server/study/self/dto/reponse/SelfStudyScriptRes.java
  server/src/main/java/com/inha/server/study/self/dto/request/EndSelfStudyReadReq.java
  server/src/main/java/com/inha/server/study/self/dto/request/EndSelfStudyWriteReq.java
  server/src/main/java/com/inha/server/study/self/dto/request/SelfStudyReq.java
  server/src/main/java/com/inha/server/study/self/dto/request/SelfStudyScriptReq.java
  server/src/main/java/com/inha/server/study/self/model/SelfStudy.java
  server/src/main/java/com/inha/server/study/self/repository/SelfStudyRepository.java
  server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java
Labels: BE, Refactor

#182 GET /self-study 파라미터 전달 방식 변경
  server/src/main/java/com/inha/server/study/self/controller/SelfStudyController.java
  server/src/main/java/com/inha/server/study/self/dto/request/SelfStudyScriptReq.java
Labels: BE

#185 stt, tts 언어 목록 업데이트
  server/src/main/java/com/inha/server/language/enumtype/language.java
Labels: BE

#187 /language 호출 시 tts, stt 값도 넘겨주도록
  server/src/main/java/com/inha/server/language/dto/response/LanguageDto.java
  server/src/main/java/com/inha/server/language/service/LanguageService.java
Labels: BE

#189 CORS DELETE 추가
  server/src/main/java/com/inha/server/oauth/security/SecurityConfig.java
Labels: BE

#192 셀프 스터디 쓰기 데이터 전송 & 반환 형태 수정
  server/src/main/java/com/inha/server/study/self/dto/request/EndSelfStudyWriteReq.java
  server/src/main/java/com/inha/server/study/self/model/SelfStudy.java
Labels: BE

#193 완료된 셀프 스터디는 삭제하지 못하도록 수정
  server/src/main/java/com/inha/server/study/self/model/SelfStudy.java
  server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java
Labels: bug, BE

#194 GET /user/achieve API 구현
  server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
  server/src/main/java/com/inha/server/mypage/dto/response/AchievementRes.java
  server/src/main/java/com/inha/server/mypage/service/MyPageService.java
  server/src/main/java/com/inha/server/oauth/service/OAuthService.java
  server/src/main/java/com/inha/server/study/self/model/SelfStudy.java
  server/src/main/java/com/inha/server/study/self/repository/SelfStudyRepository.java
  server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java
  server/src/main/java/com/inha/server/user/model/User.java
  server/src/main/java/com/inha/server/user/service/UserService.java
Labels: BE

#195 POST /self-study/read API 재구현
  server/build.gradle
  server/src/main/java/com/inha/server/study/self/controller/SelfStudyController.java
  server/src/main/java/com/inha/server/study/self/dto/request/EndSelfStudyReadReq.java
  server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java
Labels: BE, Refactor

#196 FE 셀프 스터디 기능 추가
  client/components/ChatInputBar/index.tsx
  client/components/CreateSelfStudy/index.tsx
  client/components/SelfStudyController/index.tsx
  client/components/SelfStudyPanel/AudioButton/index.tsx
  client/components/SelfStudyPanel/SelfStudyPanelRead/index.tsx
  client/components/SelfStudyPanel/SelfStudyPanelReadDone/index.tsx
  client/components/SelfStudyPanel/SelfStudyPanelWrite/index.tsx
  client/components/SelfStudyPanel/SelfStudyPanelWrite/style.ts
  client/components/SelfStudyPanel/SelfStudyPanelWriteDone/index.tsx
  client/components/SelfStudyPanel/index.tsx
  client/components/SelfStudyPanel/style.ts
  client/components/StudyCardList/index.tsx
  client/global.d.ts
  client/next.config.js
  client/package.json
  client/pages/api/self-study/[selfStudyId].ts
  client/pages/api/self-study/list.ts
  client/pages/selfStudy/read.tsx
  client/pages/selfStudy/view/read.tsx
  client/pages/selfStudy/view/write.tsx
  client/pages/selfStudy/write.tsx
  client/states/selfStudy.ts
  client/utils/api.ts
  client/utils/date.ts
  client/utils/record.ts
  client/utils/speechRecognition.ts
  client/yarn.lock
Labels: bug, FE

#197 GET /self-study/{selfStudyId} API 구현
  server/src/main/java/com/inha/server/study/self/controller/SelfStudyController.java
  server/src/main/java/com/inha/server/study/self/dto/reponse/SelfStudyGetRes.java
  server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java
Labels: BE

#200 BE hotfix 그룹 스터디 페이징 처리 수정
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
Labels: BE, Refactor

#198 ~ 2023.05.30 작업사항
  client/components/ChatInputBar/index.tsx
  client/components/CreateSelfStudy/index.tsx
  client/components/SelfStudyController/index.tsx
  client/components/SelfStudyPanel/AudioButton/index.tsx
  client/components/SelfStudyPanel/SelfStudyPanelRead/index.tsx
  client/components/SelfStudyPanel/SelfStudyPanelReadDone/index.tsx
  client/components/SelfStudyPanel/SelfStudyPanelWrite/index.tsx
  client/components/SelfStudyPanel/SelfStudyPanelWrite/style.ts
  client/components/SelfStudyPanel/SelfStudyPanelWriteDone/index.tsx
  client/components/SelfStudyPanel/index.tsx
  client/components/SelfStudyPanel/style.ts
  client/components/StudyCardList/index.tsx
  client/global.d.ts
  client/next.config.js
  client/package.json
  client/pages/api/self-study/[selfStudyId].ts
  client/pages/api/self-study/list.ts
  client/pages/selfStudy/read.tsx
  client/pages/selfStudy/view/read.tsx
  client/pages/selfStudy/view/write.tsx
  client/pages/selfStudy/write.tsx
  client/states/selfStudy.ts
  client/utils/api.ts
  client/utils/date.ts
  client/utils/record.ts
  client/utils/speechRecognition.ts
  client/yarn.lock
  server/build.gradle
  server/src/main/java/com/inha/server/chatGPT/model/Script.java
  server/src/main/java/com/inha/server/language/dto/response/LanguageDto.java
  server/src/main/java/com/inha/server/language/enumtype/language.java
  server/src/main/java/com/inha/server/language/service/LanguageService.java
  server/src/main/java/com/inha/server/mongodb/config/MongoDbConfig.java
  server/src/main/java/com/inha/server/mongodb/config/ReactiveMongoDbConfig.java
  server/src/main/java/com/inha/server/mypage/controller/MyPageController.java
  server/src/main/java/com/inha/server/mypage/dto/response/AchievementRes.java
  server/src/main/java/com/inha/server/mypage/service/MyPageService.java
  server/src/main/java/com/inha/server/oauth/security/SecurityConfig.java
  server/src/main/java/com/inha/server/oauth/service/OAuthService.java
  server/src/main/java/com/inha/server/study/group/controller/GeneralChatController.java
  server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
  server/src/main/java/com/inha/server/study/group/dto/request/PostGeneralChatReq.java
  server/src/main/java/com/inha/server/study/group/dto/response/GetGroupStudyInfoRes.java
  server/src/main/java/com/inha/server/study/group/model/GeneralChat.java
  server/src/main/java/com/inha/server/study/group/model/GeneralContent.java
  server/src/main/java/com/inha/server/study/group/repository/GeneralChatRepository.java
  server/src/main/java/com/inha/server/study/group/service/ChatService.java
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
  server/src/main/java/com/inha/server/study/self/controller/SelfStudyController.java
  server/src/main/java/com/inha/server/study/self/dto/reponse/SelfStudyCreateRes.java
  server/src/main/java/com/inha/server/study/self/dto/reponse/SelfStudyGetRes.java
  server/src/main/java/com/inha/server/study/self/dto/reponse/SelfStudyScriptRes.java
  server/src/main/java/com/inha/server/study/self/dto/request/EndSelfStudyReadReq.java
  server/src/main/java/com/inha/server/study/self/dto/request/EndSelfStudyWriteReq.java
  server/src/main/java/com/inha/server/study/self/dto/request/SelfStudyReq.java
  server/src/main/java/com/inha/server/study/self/model/SelfStudy.java
  server/src/main/java/com/inha/server/study/self/repository/SelfStudyRepository.java
  server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java
  server/src/main/java/com/inha/server/user/model/User.java
  server/src/main/java/com/inha/server/user/service/UserService.java
Labels: FE, BE, Refactor

#202 로그인 인증 만료시 처리
  client/components/EventListener/index.tsx
  client/pages/_app.tsx
  client/utils/api.ts
Labels: bug, FE

#205 모든 페이지에 title 지정
  client/pages/createStudyGroup/index.tsx
  client/pages/findStudyGroup/index.tsx
  client/pages/index.tsx
  client/pages/myPage/index.tsx
  client/pages/postView/[groupStudyId].tsx
  client/pages/selfStudy/create/read.tsx
  client/pages/selfStudy/create/write.tsx
  client/pages/selfStudy/index.tsx
  client/pages/selfStudy/read.tsx
  client/pages/selfStudy/view/read.tsx
  client/pages/selfStudy/view/write.tsx
  client/pages/selfStudy/write.tsx
  client/pages/studyGroup/[groupId].tsx
  client/pages/studyGroup/index.tsx
Labels: FE
