Repository inha-talktalk/TalkTalk, pull requests merged in 2023-06, with the labels that each got.

#207 FE 그룹 스터디 수락 컴포넌트 작성 및 적용
  client/components/GroupStudyController/GroupStudySetting/OwnerSetting/index.tsx
  client/components/GroupStudyController/GroupStudySetting/OwnerSetting/style.ts
  client/components/GroupStudyController/GroupStudySetting/index.tsx
  client/components/GroupStudyController/GroupStudySetting/style.ts
  client/components/GroupStudyController/index.tsx
  client/global.d.ts
  client/pages/studyGroup/[groupId].tsx
  client/utils/api.ts
Labels: FE

#211 BE JWT 만료시 예외처리
  server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
Labels: BE, Refactor

#216 BE 셀프 스터디 공유 기능 구현
  server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
  server/src/main/java/com/inha/server/study/group/dto/response/GetSelfStudySharedListRes.java
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
  server/src/main/java/com/inha/server/study/self/controller/SelfStudyController.java
  server/src/main/java/com/inha/server/study/self/model/SelfStudyShare.java
  server/src/main/java/com/inha/server/study/self/repository/SelfStudyShareRepository.java
  server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java
Labels: BE

#215 BE 그룹 스터디 일반 채팅 구현
  server/build.gradle
  server/src/main/java/com/inha/server/mongodb/config/ReactiveMongoDbConfig.java
  server/src/main/java/com/inha/server/study/group/controller/GeneralChatController.java
  server/src/main/java/com/inha/server/study/group/dto/response/GetGeneralChatListRes.java
  server/src/main/java/com/inha/server/study/group/model/GeneralChat.java
  server/src/main/java/com/inha/server/study/group/repository/GeneralChatRepository.java
  server/src/main/java/com/inha/server/study/group/service/ChatService.java
Labels: BE, Refactor

#218 BE hotfix 그룹 스터디 일반 채팅 조회 수정
  server/src/main/java/com/inha/server/study/group/controller/GeneralChatController.java
  server/src/main/java/com/inha/server/study/group/service/ChatService.java
Labels: BE, Refactor

#220 BE hotfix 그룹 스터디 일반 채팅 조회 예외처리
  server/src/main/java/com/inha/server/study/group/service/ChatService.java
Labels: BE, Refactor

#221 전달 데이터에 StudyType 추가
  server/src/main/java/com/inha/server/study/self/model/SelfStudyShare.java
  server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java
Labels: BE

#222 일반 채팅 내역 조회 엣지 케이스 예외처리 추가
  server/src/main/java/com/inha/server/study/group/service/ChatService.java
Labels: BE, Refactor

#226 FE 채팅 기능 구현
  client/components/GroupStudyChat/ChatSlot/index.tsx
  client/components/GroupStudyChat/index.tsx
  client/components/SelfStudyController/index.tsx
  client/components/SelfStudySharePanel/index.tsx
  client/global.d.ts
  client/states/groupStudy.ts
  client/utils/api.ts
  client/utils/date.ts
Labels: FE

#227 FE 모달 안닫히는 문제 및 기본 선택 채널 수정
  client/components/SelfStudyController/index.tsx
  client/components/SelfStudySharePanel/index.tsx
  client/states/groupStudy.ts
Labels: bug, FE

#225 BE hotfix 일반 채팅 조회 초기 상태 예외처리
  server/src/main/java/com/inha/server/study/group/service/ChatService.java
Labels: BE, Refactor

#228 ~2023.06.12 작업사항
  client/components/ChatBubble/index.tsx
  client/components/EventListener/index.tsx
  client/components/GroupStudyChat/ChatSlot/index.tsx
  client/components/GroupStudyChat/index.tsx
  client/components/GroupStudyController/GroupStudySetting/OwnerSetting/index.tsx
  client/components/GroupStudyController/GroupStudySetting/OwnerSetting/style.ts
  client/components/GroupStudyController/GroupStudySetting/index.tsx
  client/components/GroupStudyController/GroupStudySetting/style.ts
  client/components/GroupStudyController/index.tsx
  client/components/InfoBanner/index.tsx
  client/components/SelfStudyController/index.tsx
  client/components/SelfStudyPanel/AudioButton/index.tsx
  client/components/SelfStudyPanel/SelfStudyPanelRead/index.tsx
  client/components/SelfStudyPanel/SelfStudyPanelReadDone/index.tsx
  client/components/SelfStudyPanel/SelfStudyPanelWriteDone/index.tsx
  client/components/SelfStudyPanel/index.tsx
  client/components/SelfStudySharePanel/index.tsx
  client/components/StudyCard/index.tsx
  client/components/StudyCell/index.tsx
  client/global.d.ts
  client/pages/_app.tsx
  client/pages/createStudyGroup/index.tsx
  client/pages/findStudyGroup/index.tsx
  client/pages/index.tsx
  client/pages/myPage/index.tsx
  client/pages/postView/[groupStudyId].tsx
  client/pages/selfStudy/create/read.tsx
  client/pages/selfStudy/create/write.tsx
  client/pages/selfStudy/index.tsx
  client/pages/selfStudy/read.tsx
  client/pages/selfStudy/view/read.tsx
  client/pages/selfStudy/view/write.tsx
  client/pages/selfStudy/write.tsx
  client/pages/studyGroup/[groupId].tsx
  client/pages/studyGroup/index.tsx
  client/states/groupStudy.ts
  client/utils/api.ts
  client/utils/audio.ts
  client/utils/date.ts
  server/build.gradle
  server/src/main/java/com/inha/server/mongodb/config/ReactiveMongoDbConfig.java
  server/src/main/java/com/inha/server/study/group/controller/GeneralChatController.java
  server/src/main/java/com/inha/server/study/group/controller/GroupStudyController.java
  server/src/main/java/com/inha/server/study/group/dto/response/GetGeneralChatListRes.java
  server/src/main/java/com/inha/server/study/group/dto/response/GetSelfStudySharedListRes.java
  server/src/main/java/com/inha/server/study/group/model/GeneralChat.java
  server/src/main/java/com/inha/server/study/group/repository/GeneralChatRepository.java
  server/src/main/java/com/inha/server/study/group/service/ChatService.java
  server/src/main/java/com/inha/server/study/group/service/GroupStudyService.java
  server/src/main/java/com/inha/server/study/self/controller/SelfStudyController.java
  server/src/main/java/com/inha/server/study/self/dto/reponse/SelfStudyGetListRes.java
  server/src/main/java/com/inha/server/study/self/dto/reponse/SelfStudySimpleListRes.java
  server/src/main/java/com/inha/server/study/self/model/SelfStudyShare.java
  server/src/main/java/com/inha/server/study/self/repository/SelfStudyRepository.java
  server/src/main/java/com/inha/server/study/self/repository/SelfStudyShareRepository.java
  server/src/main/java/com/inha/server/study/self/service/SelfStudyService.java
  server/src/main/java/com/inha/server/user/util/TokenProvider.java
Labels: bug, FE, BE, Refactor
